language: node_js
node_js:
  - "5.7"
install:
  - npm install
  - npm install sqlite3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - npm run test-karma
compiler: clang-3.6
env:
  - CXX=clang-3.6 KARMA_BROWSER=Firefox
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
