approvals:
  # PR needs at least 2 approvals
  minimum: 2
  # approval = comment that matches this regex
  pattern: "(:\\+1:|👍)"
  from:
    # commenter must be either one of:
    # a public zalando org member
    orgs:
      - zalando
    # a collaborator of the repo
    collaborators: true
    # this guy
    users:
      - mfellner
autobranch:
  # things in curly brackets are variables that
  # will be replaced. possible variables:
  # - number: the issue number
  # - title: the issue title
  # - labels: the labels of the issue at opening time
  pattern: "{number}-{title}"
  # restrict branch name to maximum this many characters
  length: 60
