SESSION_SECRET: secret
GITHUB_CLIENT_ID: id
GITHUB_CLIENT_SECRET: secret
GITHUB_SCOPES:
  - user:email
  - repo:status
  - write:repo_hook
GITHUB_URL: https://api.github.com
HOST_ADDR: http://127.0.0.1:8080
NODE_ENV: development
LOG_FORMAT: dev
APP_PORT: 3000
STATIC_DIR: ./dist/client
LEVEL_DB: ./zappr.db
DB_DRIVER: sqlite
DB_NAME: zappr
#DB_USER: postgres
#DB_PASS: postgres
#DB_HOST: 192.168.99.100
#DB_PORT: 5432
#DB_SCHEMA: zappr
SQLITE_FILE: ./zappr.sqlite
