# Zappr application configuration: opensource

# path to zapprfile in repository
VALID_ZAPPR_FILE_PATHS:
  - "/.zappr.yaml"
  - "/.zappr.yml"
ZAPPR_DEFAULT_CONFIG:
  autobranch:
    pattern: "{number}-{title}"
    length: 60
  commit:
    message:
      patterns:
        - "^#[0-9]+"
  approvals:
    minimum: 2
    pattern: "^(:\\+1:|👍)$"
